package subnetworkConnection;


/**
* subnetworkConnection/NetworkRouted_T.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from subnetworkConnection.idl
* Wednesday, June 15, 2016 7:24:41 PM COT
*/


/**
   * <p>Network routed, indicates if the route must be or is computed and
   * implemented at the network level. NR_YES indicates that the
   * route must be / is computed at the network. NR_NO indicates that the route 
   * must not be / is not computed at the network. NR_NA indicates that the 
   * route can be computed anywhere.</p>
   * 
   * <p>If rerouting is allowed, this attribute will indicate who last rerouted 
   * the SNC, the network (NR_YES) or the EMS (NR_NO).</p>
   **/
public class NetworkRouted_T implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static subnetworkConnection.NetworkRouted_T[] __array = new subnetworkConnection.NetworkRouted_T [__size];

  public static final int _NR_NA = 0;
  public static final subnetworkConnection.NetworkRouted_T NR_NA = new subnetworkConnection.NetworkRouted_T(_NR_NA);
  public static final int _NR_NO = 1;
  public static final subnetworkConnection.NetworkRouted_T NR_NO = new subnetworkConnection.NetworkRouted_T(_NR_NO);
  public static final int _NR_YES = 2;
  public static final subnetworkConnection.NetworkRouted_T NR_YES = new subnetworkConnection.NetworkRouted_T(_NR_YES);

  public int value ()
  {
    return __value;
  }

  public static subnetworkConnection.NetworkRouted_T from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected NetworkRouted_T (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class NetworkRouted_T
