package subnetworkConnection;

/**
* subnetworkConnection/SubnetworkConnection_THolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from subnetworkConnection.idl
* Wednesday, June 15, 2016 7:24:41 PM COT
*/

public final class SubnetworkConnection_THolder implements org.omg.CORBA.portable.Streamable
{
  public subnetworkConnection.SubnetworkConnection_T value = null;

  public SubnetworkConnection_THolder ()
  {
  }

  public SubnetworkConnection_THolder (subnetworkConnection.SubnetworkConnection_T initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = subnetworkConnection.SubnetworkConnection_THelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    subnetworkConnection.SubnetworkConnection_THelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return subnetworkConnection.SubnetworkConnection_THelper.type ();
  }

}
