package softwareAndDataManager;


/**
* softwareAndDataManager/Current_OperationStatus_THelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from softwareAndDataManager.idl
* Wednesday, June 15, 2016 7:24:41 PM COT
*/


/**
   * <p>This enum identifies the status of a managed element with respect to 
   * current database backup operation.</p>
   * <p>Initially when the EMS is started the Operational status will be set to 
   * COS_Idle.</p>
   *
   * <p>The current operation status values are defined as follows:<p>
   * <ol>
   * <li>COS_Idle: no database backup operation has been performed since EMS 
   * last (re)started (boot).</li>
   * <li>COS_Pending: a backup operation has been requested but has not yet 
   * started.</li>
   * <li>COS_InProgress: a backup operation is being performed.</li>
   * <il>COS_Completed: last backup operation was successful.</li>
   * <il>COS_Aborted: last backup operation failed.</li>
   * </ol><br>
   **/
abstract public class Current_OperationStatus_THelper
{
  private static String  _id = "IDL:mtnm.tmforum.org/softwareAndDataManager/Current_OperationStatus_T:1.0";

  public static void insert (org.omg.CORBA.Any a, softwareAndDataManager.Current_OperationStatus_T that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static softwareAndDataManager.Current_OperationStatus_T extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (softwareAndDataManager.Current_OperationStatus_THelper.id (), "Current_OperationStatus_T", new String[] { "COS_Idle", "COS_Pending", "COS_InProgress", "COS_Completed", "COS_Aborted"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static softwareAndDataManager.Current_OperationStatus_T read (org.omg.CORBA.portable.InputStream istream)
  {
    return softwareAndDataManager.Current_OperationStatus_T.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, softwareAndDataManager.Current_OperationStatus_T value)
  {
    ostream.write_long (value.value ());
  }

}
