package equipment;

/**
* equipment/HolderState_THolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from equipment.idl
* Wednesday, June 15, 2016 7:24:35 PM COT
*/


/**
   * <p>Indicates the state of the equipment holder object with respect to its 
   * directly contained equipment.
   * See <a href=../../../supportingDocumentation/SD1-10_EquipmentModel.pdf >SD1-10 Equipment Model</a>. 
   * Applies when the equipment holder can contain equipment 
   * objects.</p>
   **/
public final class HolderState_THolder implements org.omg.CORBA.portable.Streamable
{
  public equipment.HolderState_T value = null;

  public HolderState_THolder ()
  {
  }

  public HolderState_THolder (equipment.HolderState_T initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = equipment.HolderState_THelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    equipment.HolderState_THelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return equipment.HolderState_THelper.type ();
  }

}
