package protection;


/**
* protection/ProtectionType_T.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from protection.idl
* Wednesday, June 15, 2016 7:24:41 PM COT
*/


/**
   * <p>The protection type identifies whether a protection switch
   * is an MS protection switch or an SNCP protection switch.</p>
   * <p>It should be noted that although the term MSP was chosen 
   * as the original specific protection scheme to which the related behaviour
   * applied was Multiplex Section Protection, the label is now more generally 
   * applied to any 1+1 or 1:N Trail protection scheme.</p>
   **/
public class ProtectionType_T implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static protection.ProtectionType_T[] __array = new protection.ProtectionType_T [__size];

  public static final int _PT_MSP_APS = 0;
  public static final protection.ProtectionType_T PT_MSP_APS = new protection.ProtectionType_T(_PT_MSP_APS);
  public static final int _PT_SNCP = 1;
  public static final protection.ProtectionType_T PT_SNCP = new protection.ProtectionType_T(_PT_SNCP);

  public int value ()
  {
    return __value;
  }

  public static protection.ProtectionType_T from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected ProtectionType_T (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class ProtectionType_T
