package CosTrading.RegisterPackage;

/**
* CosTrading/RegisterPackage/MandatoryPropertyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosTrading.idl
* Wednesday, June 15, 2016 7:24:33 PM COT
*/

public final class MandatoryPropertyHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.RegisterPackage.MandatoryProperty value = null;

  public MandatoryPropertyHolder ()
  {
  }

  public MandatoryPropertyHolder (CosTrading.RegisterPackage.MandatoryProperty initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.RegisterPackage.MandatoryPropertyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.RegisterPackage.MandatoryPropertyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.RegisterPackage.MandatoryPropertyHelper.type ();
  }

}
