package flowDomainFragment;


/**
* flowDomainFragment/FDFrCreateData_T.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flowDomainFragment.idl
* Wednesday, June 15, 2016 7:24:36 PM COT
*/

public final class FDFrCreateData_T implements org.omg.CORBA.portable.IDLEntity
{
  public globaldefs.NameAndStringValue_T name[] = null;
  public String userLabel = null;
  public boolean forceUniqueness = false;
  public String owner = null;
  public String networkAccessDomain = null;
  public globaldefs.ConnectionDirection_T direction = null;
  public performance.AdministrativeState_T administrativeState = null;
  public transmissionParameters.LayeredParameters_T transmissionParams = null;
  public boolean fullRoute = false;
  public String fdfrType = null;
  public globaldefs.NameAndStringValue_T additionalCreationInfo[] = null;

  public FDFrCreateData_T ()
  {
  } // ctor

  public FDFrCreateData_T (globaldefs.NameAndStringValue_T[] _name, String _userLabel, boolean _forceUniqueness, String _owner, String _networkAccessDomain, globaldefs.ConnectionDirection_T _direction, performance.AdministrativeState_T _administrativeState, transmissionParameters.LayeredParameters_T _transmissionParams, boolean _fullRoute, String _fdfrType, globaldefs.NameAndStringValue_T[] _additionalCreationInfo)
  {
    name = _name;
    userLabel = _userLabel;
    forceUniqueness = _forceUniqueness;
    owner = _owner;
    networkAccessDomain = _networkAccessDomain;
    direction = _direction;
    administrativeState = _administrativeState;
    transmissionParams = _transmissionParams;
    fullRoute = _fullRoute;
    fdfrType = _fdfrType;
    additionalCreationInfo = _additionalCreationInfo;
  } // ctor

} // class FDFrCreateData_T
