package flowDomainFragment;


/**
* flowDomainFragment/FDFrIterator_I.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flowDomainFragment.idl
* Wednesday, June 15, 2016 7:24:36 PM COT
*/

public interface FDFrIterator_I extends FDFrIterator_IOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FDFrIterator_I
