package flowDomainFragment;


/**
* flowDomainFragment/MFDFrIterator_I.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flowDomainFragment.idl
* Wednesday, June 15, 2016 7:24:36 PM COT
*/


/**
   * <p>In order to allow the NMS to deal with a large number of objects,
   * iterators are used.</p>
   **/
public interface MFDFrIterator_I extends MFDFrIterator_IOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MFDFrIterator_I
