package guiCutThrough;


/**
* guiCutThrough/GCTProfileInfo_THelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from guiCutThrough.idl
* Wednesday, June 15, 2016 7:24:37 PM COT
*/

abstract public class GCTProfileInfo_THelper
{
  private static String  _id = "IDL:mtnm.tmforum.org/guiCutThrough/GCTProfileInfo_T:1.0";

  public static void insert (org.omg.CORBA.Any a, guiCutThrough.GCTProfileInfo_T that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static guiCutThrough.GCTProfileInfo_T extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = guiCutThrough.ServerLaunchCapability_THelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "serverLaunchCapability",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "gctHostname",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "emsGctPlatform",
            _tcOf_members0,
            null);
          _tcOf_members0 = guiCutThrough.GuiCutThroughData_THelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (guiCutThrough.GuiCutThroughDataList_THelper.id (), "GuiCutThroughDataList_T", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "guiCutThroughDataList",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (guiCutThrough.GCTProfileInfo_THelper.id (), "GCTProfileInfo_T", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static guiCutThrough.GCTProfileInfo_T read (org.omg.CORBA.portable.InputStream istream)
  {
    guiCutThrough.GCTProfileInfo_T value = new guiCutThrough.GCTProfileInfo_T ();
    value.serverLaunchCapability = guiCutThrough.ServerLaunchCapability_THelper.read (istream);
    value.gctHostname = istream.read_string ();
    value.emsGctPlatform = istream.read_string ();
    value.guiCutThroughDataList = guiCutThrough.GuiCutThroughDataList_THelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, guiCutThrough.GCTProfileInfo_T value)
  {
    guiCutThrough.ServerLaunchCapability_THelper.write (ostream, value.serverLaunchCapability);
    ostream.write_string (value.gctHostname);
    ostream.write_string (value.emsGctPlatform);
    guiCutThrough.GuiCutThroughDataList_THelper.write (ostream, value.guiCutThroughDataList);
  }

}
