package transmissionDescriptor;

/**
* transmissionDescriptor/TPorMFDorFDFr_THolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from transmissionDescriptor.idl
* Wednesday, June 15, 2016 7:24:43 PM COT
*/

public final class TPorMFDorFDFr_THolder implements org.omg.CORBA.portable.Streamable
{
  public transmissionDescriptor.TPorMFDorFDFr_T value = null;

  public TPorMFDorFDFr_THolder ()
  {
  }

  public TPorMFDorFDFr_THolder (transmissionDescriptor.TPorMFDorFDFr_T initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = transmissionDescriptor.TPorMFDorFDFr_THelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    transmissionDescriptor.TPorMFDorFDFr_THelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return transmissionDescriptor.TPorMFDorFDFr_THelper.type ();
  }

}
