package emsSession;

/**
* emsSession/EmsSession_IHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from emsSession.idl
* Wednesday, June 15, 2016 7:24:35 PM COT
*/


/** 
   * <p>A handle to an instance of this interface is gained via the
   * emsSessionInterface parameter of the getEmsSession()
   * operation in EmsSessionFactory_I.</p>
   */
public final class EmsSession_IHolder implements org.omg.CORBA.portable.Streamable
{
  public emsSession.EmsSession_I value = null;

  public EmsSession_IHolder ()
  {
  }

  public EmsSession_IHolder (emsSession.EmsSession_I initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = emsSession.EmsSession_IHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    emsSession.EmsSession_IHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return emsSession.EmsSession_IHelper.type ();
  }

}
