package notifications;


/**
* notifications/AlarmId_T.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notifications.idl
* Wednesday, June 15, 2016 7:24:40 PM COT
*/

public final class AlarmId_T implements org.omg.CORBA.portable.IDLEntity
{
  public globaldefs.NameAndStringValue_T objectName[] = null;
  public short layerRate = (short)0;
  public String probableCause = null;
  public String probableCauseQualifier = null;

  public AlarmId_T ()
  {
  } // ctor

  public AlarmId_T (globaldefs.NameAndStringValue_T[] _objectName, short _layerRate, String _probableCause, String _probableCauseQualifier)
  {
    objectName = _objectName;
    layerRate = _layerRate;
    probableCause = _probableCause;
    probableCauseQualifier = _probableCauseQualifier;
  } // ctor

} // class AlarmId_T
