package notifications;

/**
* notifications/NameAndAnyValue_THolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notifications.idl
* Wednesday, June 15, 2016 7:24:40 PM COT
*/

public final class NameAndAnyValue_THolder implements org.omg.CORBA.portable.Streamable
{
  public notifications.NameAndAnyValue_T value = null;

  public NameAndAnyValue_THolder ()
  {
  }

  public NameAndAnyValue_THolder (notifications.NameAndAnyValue_T initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = notifications.NameAndAnyValue_THelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    notifications.NameAndAnyValue_THelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return notifications.NameAndAnyValue_THelper.type ();
  }

}
