package flowDomain;

/**
* flowDomain/FDCreateData_THolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flowDomain.idl
* Wednesday, June 15, 2016 7:24:36 PM COT
*/

public final class FDCreateData_THolder implements org.omg.CORBA.portable.Streamable
{
  public flowDomain.FDCreateData_T value = null;

  public FDCreateData_THolder ()
  {
  }

  public FDCreateData_THolder (flowDomain.FDCreateData_T initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = flowDomain.FDCreateData_THelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    flowDomain.FDCreateData_THelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return flowDomain.FDCreateData_THelper.type ();
  }

}
