package flowDomain;


/**
* flowDomain/FlowDomainMgr_IHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flowDomain.idl
* Wednesday, June 15, 2016 7:24:36 PM COT
*/


/**
   * <p>The FlowDomainMgr_I is used to gain access to flow domains,
   * matrix flow domains, flow domain fragments and their operations.</p>
   *

   * <p>A handle to an instance of this interface is gained via the
   * emsSession::EmsSession_I::getManager() operation.</p>
   **/
abstract public class FlowDomainMgr_IHelper
{
  private static String  _id = "IDL:mtnm.tmforum.org/flowDomain/FlowDomainMgr_I:1.0";

  public static void insert (org.omg.CORBA.Any a, flowDomain.FlowDomainMgr_I that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static flowDomain.FlowDomainMgr_I extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (flowDomain.FlowDomainMgr_IHelper.id (), "FlowDomainMgr_I");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static flowDomain.FlowDomainMgr_I read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FlowDomainMgr_IStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, flowDomain.FlowDomainMgr_I value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static flowDomain.FlowDomainMgr_I narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof flowDomain.FlowDomainMgr_I)
      return (flowDomain.FlowDomainMgr_I)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      flowDomain._FlowDomainMgr_IStub stub = new flowDomain._FlowDomainMgr_IStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static flowDomain.FlowDomainMgr_I unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof flowDomain.FlowDomainMgr_I)
      return (flowDomain.FlowDomainMgr_I)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      flowDomain._FlowDomainMgr_IStub stub = new flowDomain._FlowDomainMgr_IStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
