package flowDomain;


/**
* flowDomain/MFDIterator_IHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flowDomain.idl
* Wednesday, June 15, 2016 7:24:36 PM COT
*/


/**
   * <p>In order to allow the NMS to deal with a large number of 
   * matrix flow domain objects, iterators are used.</p>
   **/
abstract public class MFDIterator_IHelper
{
  private static String  _id = "IDL:mtnm.tmforum.org/flowDomain/MFDIterator_I:1.0";

  public static void insert (org.omg.CORBA.Any a, flowDomain.MFDIterator_I that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static flowDomain.MFDIterator_I extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (flowDomain.MFDIterator_IHelper.id (), "MFDIterator_I");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static flowDomain.MFDIterator_I read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MFDIterator_IStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, flowDomain.MFDIterator_I value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static flowDomain.MFDIterator_I narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof flowDomain.MFDIterator_I)
      return (flowDomain.MFDIterator_I)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      flowDomain._MFDIterator_IStub stub = new flowDomain._MFDIterator_IStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static flowDomain.MFDIterator_I unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof flowDomain.MFDIterator_I)
      return (flowDomain.MFDIterator_I)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      flowDomain._MFDIterator_IStub stub = new flowDomain._MFDIterator_IStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
