package mLSNPPLink;


/**
* mLSNPPLink/MLSNPPLinkList_THolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from mLSNPPLink.idl
* Wednesday, June 15, 2016 7:24:38 PM COT
*/


/**
   * <p>Sequence of MLSNPPLink_T.<p>
   **/
public final class MLSNPPLinkList_THolder implements org.omg.CORBA.portable.Streamable
{
  public mLSNPPLink.MultiLayerSNPPLink_T value[] = null;

  public MLSNPPLinkList_THolder ()
  {
  }

  public MLSNPPLinkList_THolder (mLSNPPLink.MultiLayerSNPPLink_T[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = mLSNPPLink.MLSNPPLinkList_THelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    mLSNPPLink.MLSNPPLinkList_THelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return mLSNPPLink.MLSNPPLinkList_THelper.type ();
  }

}
