package maintenanceOps;


/**
* maintenanceOps/CurrentMaintenanceOperationList_THolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from maintenanceOps.idl
* Wednesday, June 15, 2016 7:24:37 PM COT
*/


/**
   * <p>Sequence of CurrentMaintenanceOperation_T</p>
   **/
public final class CurrentMaintenanceOperationList_THolder implements org.omg.CORBA.portable.Streamable
{
  public maintenanceOps.CurrentMaintenanceOperation_T value[] = null;

  public CurrentMaintenanceOperationList_THolder ()
  {
  }

  public CurrentMaintenanceOperationList_THolder (maintenanceOps.CurrentMaintenanceOperation_T[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = maintenanceOps.CurrentMaintenanceOperationList_THelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    maintenanceOps.CurrentMaintenanceOperationList_THelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return maintenanceOps.CurrentMaintenanceOperationList_THelper.type ();
  }

}
