package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/ClientTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyChannelAdmin.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/


/**
    * Enumeration of client types.
    */
abstract public class ClientTypeHelper
{
  private static String  _id = "IDL:omg.org/CosNotifyChannelAdmin/ClientType:1.0";

  public static void insert (org.omg.CORBA.Any a, CosNotifyChannelAdmin.ClientType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CosNotifyChannelAdmin.ClientType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (CosNotifyChannelAdmin.ClientTypeHelper.id (), "ClientType", new String[] { "ANY_EVENT", "STRUCTURED_EVENT", "SEQUENCE_EVENT"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CosNotifyChannelAdmin.ClientType read (org.omg.CORBA.portable.InputStream istream)
  {
    return CosNotifyChannelAdmin.ClientType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CosNotifyChannelAdmin.ClientType value)
  {
    ostream.write_long (value.value ());
  }

}
