package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/InterFilterGroupOperator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyChannelAdmin.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/


/**
    * Enumeration of filter group operators.
    */
public class InterFilterGroupOperator implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static CosNotifyChannelAdmin.InterFilterGroupOperator[] __array = new CosNotifyChannelAdmin.InterFilterGroupOperator [__size];

  public static final int _AND_OP = 0;
  public static final CosNotifyChannelAdmin.InterFilterGroupOperator AND_OP = new CosNotifyChannelAdmin.InterFilterGroupOperator(_AND_OP);
  public static final int _OR_OP = 1;
  public static final CosNotifyChannelAdmin.InterFilterGroupOperator OR_OP = new CosNotifyChannelAdmin.InterFilterGroupOperator(_OR_OP);

  public int value ()
  {
    return __value;
  }

  public static CosNotifyChannelAdmin.InterFilterGroupOperator from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected InterFilterGroupOperator (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class InterFilterGroupOperator
