package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/ProxyNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyChannelAdmin.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/

public final class ProxyNotFound extends org.omg.CORBA.UserException
{

  public ProxyNotFound ()
  {
    super(ProxyNotFoundHelper.id());
  } // ctor


  public ProxyNotFound (String $reason)
  {
    super(ProxyNotFoundHelper.id() + "  " + $reason);
  } // ctor

} // class ProxyNotFound
