package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/SequenceProxyPushSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyChannelAdmin.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/


/**
    * An interface for sequence proxy push suppliers.
    */
public interface SequenceProxyPushSupplierOperations  extends CosNotifyChannelAdmin.ProxySupplierOperations, CosNotifyComm.SequencePushSupplierOperations
{

  /**
         * Connect a sequence type push consumer to this proxy.
         * @parm <code>push_consumer</code> - The <code>PushConsumer</code>
         * object reference.
         * @raises AlreadyConnected If this consumer is already connected.
         * @raises TypeError Illegal consumer type.
         */
  void connect_sequence_push_consumer (CosNotifyComm.SequencePushConsumer push_consumer) throws CosEventChannelAdmin.AlreadyConnected, CosEventChannelAdmin.TypeError;

  /**
         * Causes this proxy to stop sending events to its consumer. Note
         * that events will still be queued while the connection is suspended.
         * @raises ConnectionAlreadyInactive Proxy already stopped.
         * @raises NotConnected Proxy not connected.
         */
  void suspend_connection () throws CosNotifyChannelAdmin.ConnectionAlreadyInactive, CosNotifyChannelAdmin.NotConnected;

  /**
         * Causes this proxy to start sending events to its consumer.
         * All queued events will be forwarded to the consumers.
         * @raises ConnectionAlreadyActive Proxy already started.
         * @raises NotConnected Proxy not connected.
         */
  void resume_connection () throws CosNotifyChannelAdmin.ConnectionAlreadyActive, CosNotifyChannelAdmin.NotConnected;
} // interface SequenceProxyPushSupplierOperations
