package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/SequenceProxyPullConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyChannelAdmin.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/


/**
    * An interface for sequence proxy pull consumers.
    */
public interface SequenceProxyPullConsumer extends SequenceProxyPullConsumerOperations, CosNotifyChannelAdmin.ProxyConsumer, CosNotifyComm.SequencePullConsumer
{
} // interface SequenceProxyPullConsumer
