package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/SequenceProxyPullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyChannelAdmin.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/


/**
    * An interface for sequence proxy pull consumers.
    */
public interface SequenceProxyPullConsumerOperations  extends CosNotifyChannelAdmin.ProxyConsumerOperations, CosNotifyComm.SequencePullConsumerOperations
{

  /**
         * Connect a sequence type pull supplier to this proxy.
         * @parm <code>pull_supplier</code> - The <code>PullSupplier</code>
         * object reference.
         * @raises AlreadyConnected If this supplier is already connected.
         * @raises TypeError Illegal supplier type.
         */
  void connect_sequence_pull_supplier (CosNotifyComm.SequencePullSupplier pull_supplier) throws CosEventChannelAdmin.AlreadyConnected, CosEventChannelAdmin.TypeError;

  /**
         * Causes this proxy to stop pulling events from its supplier.
         * @raises ConnectionAlreadyInactive Proxy already stopped.
         * @raises NotConnected Proxy not connected.
         */
  void suspend_connection () throws CosNotifyChannelAdmin.ConnectionAlreadyInactive, CosNotifyChannelAdmin.NotConnected;

  /**
         * Causes this proxy to start pulling events from its supplier.
         * @raises ConnectionAlreadyActive</code> - Proxy already started.
         * @raises NotConnected Proxy not connected.
         */
  void resume_connection () throws CosNotifyChannelAdmin.ConnectionAlreadyActive, CosNotifyChannelAdmin.NotConnected;
} // interface SequenceProxyPullConsumerOperations
