package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/StructuredProxyPushConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyChannelAdmin.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/


/**
    * An interface for structured proxy push consumers.
    */
public interface StructuredProxyPushConsumerOperations  extends CosNotifyChannelAdmin.ProxyConsumerOperations, CosNotifyComm.StructuredPushConsumerOperations
{

  /**
         * Connect a structured type push supplier to this proxy.
         * @parm <code>push_supplier</code> - The <code>PushSupplier</code>
         * object reference.
         * @raises AlreadyConnected If this supplier is already connected.
         */
  void connect_structured_push_supplier (CosNotifyComm.StructuredPushSupplier push_supplier) throws CosEventChannelAdmin.AlreadyConnected;
} // interface StructuredProxyPushConsumerOperations
