package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/StructuredProxyPushSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyChannelAdmin.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/


/**
    * An interface for structured proxy push suppliers.
    */
public interface StructuredProxyPushSupplier extends StructuredProxyPushSupplierOperations, CosNotifyChannelAdmin.ProxySupplier, CosNotifyComm.StructuredPushSupplier
{
} // interface StructuredProxyPushSupplier
