package CosNotifyFilter;


/**
* CosNotifyFilter/DuplicateConstraintID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyFilter.idl
* Wednesday, June 15, 2016 7:24:33 PM COT
*/


/**
    * Exception used to indicate a duplicate constraint ID.
    */
public final class DuplicateConstraintID extends org.omg.CORBA.UserException
{
  public int id = (int)0;

  public DuplicateConstraintID ()
  {
    super(DuplicateConstraintIDHelper.id());
  } // ctor

  public DuplicateConstraintID (int _id)
  {
    super(DuplicateConstraintIDHelper.id());
    id = _id;
  } // ctor


  public DuplicateConstraintID (String $reason, int _id)
  {
    super(DuplicateConstraintIDHelper.id() + "  " + $reason);
    id = _id;
  } // ctor

} // class DuplicateConstraintID
