package CosNotifyFilter;

/**
* CosNotifyFilter/InvalidConstraintHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyFilter.idl
* Wednesday, June 15, 2016 7:24:33 PM COT
*/

public final class InvalidConstraintHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyFilter.InvalidConstraint value = null;

  public InvalidConstraintHolder ()
  {
  }

  public InvalidConstraintHolder (CosNotifyFilter.InvalidConstraint initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyFilter.InvalidConstraintHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyFilter.InvalidConstraintHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyFilter.InvalidConstraintHelper.type ();
  }

}
