package CosNotifyFilter;

/**
* CosNotifyFilter/MappingFilterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyFilter.idl
* Wednesday, June 15, 2016 7:24:33 PM COT
*/


/**
    * Interface for a mapping filter.
    */
public final class MappingFilterHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyFilter.MappingFilter value = null;

  public MappingFilterHolder ()
  {
  }

  public MappingFilterHolder (CosNotifyFilter.MappingFilter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyFilter.MappingFilterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyFilter.MappingFilterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyFilter.MappingFilterHelper.type ();
  }

}
