package CosNotifyFilter;

/**
* CosNotifyFilter/UnsupportedFilterableDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyFilter.idl
* Wednesday, June 15, 2016 7:24:33 PM COT
*/

public final class UnsupportedFilterableDataHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyFilter.UnsupportedFilterableData value = null;

  public UnsupportedFilterableDataHolder ()
  {
  }

  public UnsupportedFilterableDataHolder (CosNotifyFilter.UnsupportedFilterableData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyFilter.UnsupportedFilterableDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyFilter.UnsupportedFilterableDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyFilter.UnsupportedFilterableDataHelper.type ();
  }

}
