package CosTrading.LookupPackage;


/**
* CosTrading/LookupPackage/PolicyTypeMismatch.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosTrading.idl
* Wednesday, June 15, 2016 7:24:33 PM COT
*/

public final class PolicyTypeMismatch extends org.omg.CORBA.UserException
{
  public CosTrading.Policy the_policy = null;

  public PolicyTypeMismatch ()
  {
    super(PolicyTypeMismatchHelper.id());
  } // ctor

  public PolicyTypeMismatch (CosTrading.Policy _the_policy)
  {
    super(PolicyTypeMismatchHelper.id());
    the_policy = _the_policy;
  } // ctor


  public PolicyTypeMismatch (String $reason, CosTrading.Policy _the_policy)
  {
    super(PolicyTypeMismatchHelper.id() + "  " + $reason);
    the_policy = _the_policy;
  } // ctor

} // class PolicyTypeMismatch
