package DsLogAdmin;

/**
* DsLogAdmin/AdministrativeStateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DsLogAdmin.idl
* Wednesday, June 15, 2016 7:24:34 PM COT
*/

public final class AdministrativeStateHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.AdministrativeState value = null;

  public AdministrativeStateHolder ()
  {
  }

  public AdministrativeStateHolder (DsLogAdmin.AdministrativeState initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.AdministrativeStateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.AdministrativeStateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.AdministrativeStateHelper.type ();
  }

}
