package DsLogAdmin;


/**
* DsLogAdmin/ForwardingStateHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DsLogAdmin.idl
* Wednesday, June 15, 2016 7:24:34 PM COT
*/


// logging on/off
abstract public class ForwardingStateHelper
{
  private static String  _id = "IDL:omg.org/DsLogAdmin/ForwardingState:1.0";

  public static void insert (org.omg.CORBA.Any a, DsLogAdmin.ForwardingState that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DsLogAdmin.ForwardingState extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (DsLogAdmin.ForwardingStateHelper.id (), "ForwardingState", new String[] { "on", "off"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DsLogAdmin.ForwardingState read (org.omg.CORBA.portable.InputStream istream)
  {
    return DsLogAdmin.ForwardingState.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DsLogAdmin.ForwardingState value)
  {
    ostream.write_long (value.value ());
  }

}
