package DsLogAdmin;

/**
* DsLogAdmin/InvalidParamHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DsLogAdmin.idl
* Wednesday, June 15, 2016 7:24:34 PM COT
*/

public final class InvalidParamHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.InvalidParam value = null;

  public InvalidParamHolder ()
  {
  }

  public InvalidParamHolder (DsLogAdmin.InvalidParam initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.InvalidParamHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.InvalidParamHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.InvalidParamHelper.type ();
  }

}
