package DsLogAdmin;

/**
* DsLogAdmin/InvalidRecordIdHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DsLogAdmin.idl
* Wednesday, June 15, 2016 7:24:34 PM COT
*/

public final class InvalidRecordIdHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.InvalidRecordId value = null;

  public InvalidRecordIdHolder ()
  {
  }

  public InvalidRecordIdHolder (DsLogAdmin.InvalidRecordId initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.InvalidRecordIdHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.InvalidRecordIdHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.InvalidRecordIdHelper.type ();
  }

}
