package DsLogAdmin;

/**
* DsLogAdmin/InvalidConstraintHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DsLogAdmin.idl
* Wednesday, June 15, 2016 7:24:34 PM COT
*/

public final class InvalidConstraintHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.InvalidConstraint value = null;

  public InvalidConstraintHolder ()
  {
  }

  public InvalidConstraintHolder (DsLogAdmin.InvalidConstraint initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.InvalidConstraintHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.InvalidConstraintHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.InvalidConstraintHelper.type ();
  }

}
