package DsLogAdmin;


/**
* DsLogAdmin/RecordIdListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DsLogAdmin.idl
* Wednesday, June 15, 2016 7:24:34 PM COT
*/

public final class RecordIdListHolder implements org.omg.CORBA.portable.Streamable
{
  public long value[] = null;

  public RecordIdListHolder ()
  {
  }

  public RecordIdListHolder (long[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.RecordIdListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.RecordIdListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.RecordIdListHelper.type ();
  }

}
