package DsLogAdmin;


/**
* DsLogAdmin/UnsupportedQoSHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DsLogAdmin.idl
* Wednesday, June 15, 2016 7:24:34 PM COT
*/

abstract public class UnsupportedQoSHelper
{
  private static String  _id = "IDL:omg.org/DsLogAdmin/UnsupportedQoS:1.0";

  public static void insert (org.omg.CORBA.Any a, DsLogAdmin.UnsupportedQoS that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DsLogAdmin.UnsupportedQoS extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ushort);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (DsLogAdmin.QoSTypeHelper.id (), "QoSType", _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (DsLogAdmin.QoSListHelper.id (), "QoSList", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "denied",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (DsLogAdmin.UnsupportedQoSHelper.id (), "UnsupportedQoS", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DsLogAdmin.UnsupportedQoS read (org.omg.CORBA.portable.InputStream istream)
  {
    DsLogAdmin.UnsupportedQoS value = new DsLogAdmin.UnsupportedQoS ();
    // read and discard the repository ID
    istream.read_string ();
    value.denied = DsLogAdmin.QoSListHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DsLogAdmin.UnsupportedQoS value)
  {
    // write the repository ID
    ostream.write_string (id ());
    DsLogAdmin.QoSListHelper.write (ostream, value.denied);
  }

}
