package transmissionParameters;


/**
* transmissionParameters/LayeredParameters_T.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from transmissionParameters.idl
* Wednesday, June 15, 2016 7:24:44 PM COT
*/

public final class LayeredParameters_T implements org.omg.CORBA.portable.IDLEntity
{
  public short layer = (short)0;
  public globaldefs.NameAndStringValue_T transmissionParams[] = null;

  public LayeredParameters_T ()
  {
  } // ctor

  public LayeredParameters_T (short _layer, globaldefs.NameAndStringValue_T[] _transmissionParams)
  {
    layer = _layer;
    transmissionParams = _transmissionParams;
  } // ctor

} // class LayeredParameters_T
