package nmsSession;

/**
* nmsSession/NmsSession_IHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from nmsSession.idl
* Wednesday, June 15, 2016 7:24:39 PM COT
*/


/** 
   * <p>This interface is instantiated at the NMS. The NMS passes
   * a handle to an instance of this interface in the client 
   * parameter of the emsSessionFactory::EmsSessionFactory_I::getEmsSession()
   * operation in EmsSessionFactory_I.</p>
   */
public final class NmsSession_IHolder implements org.omg.CORBA.portable.Streamable
{
  public nmsSession.NmsSession_I value = null;

  public NmsSession_IHolder ()
  {
  }

  public NmsSession_IHolder (nmsSession.NmsSession_I initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nmsSession.NmsSession_IHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nmsSession.NmsSession_IHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nmsSession.NmsSession_IHelper.type ();
  }

}
