package callSNC;


/**
* callSNC/RouteGroupInfo_T.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from callSNC.idl
* Wednesday, June 15, 2016 7:24:30 PM COT
*/

public final class RouteGroupInfo_T implements org.omg.CORBA.portable.IDLEntity
{
  public globaldefs.NameAndStringValue_T sNCname[] = null;
  public String routeGroupLabel = null;

  public RouteGroupInfo_T ()
  {
  } // ctor

  public RouteGroupInfo_T (globaldefs.NameAndStringValue_T[] _sNCname, String _routeGroupLabel)
  {
    sNCname = _sNCname;
    routeGroupLabel = _routeGroupLabel;
  } // ctor

} // class RouteGroupInfo_T
