package CosNotifyComm;


/**
* CosNotifyComm/SequencePushConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/


/**
    * An interface for sequence push consumers.
    */
public interface SequencePushConsumer extends SequencePushConsumerOperations, CosNotifyComm.NotifyPublish, org.omg.CORBA.portable.IDLEntity 
{
} // interface SequencePushConsumer
