package CosNotifyComm;


/**
* CosNotifyComm/StructuredPushSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/


/**
    * An interface for structured push suppliers.
    */
public interface StructuredPushSupplierOperations  extends CosNotifyComm.NotifySubscribeOperations
{

  /**
         * Disconnect this push supplier.
         */
  void disconnect_structured_push_supplier ();
} // interface StructuredPushSupplierOperations
