package CosNotifyComm;


/**
* CosNotifyComm/StructuredPullConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/


/**
    * An interface for structured pull consumers.
    */
public interface StructuredPullConsumer extends StructuredPullConsumerOperations, CosNotifyComm.NotifyPublish, org.omg.CORBA.portable.IDLEntity 
{
} // interface StructuredPullConsumer
