package CosNotification;


/**
* CosNotification/AdminPropertiesAdminPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/


/**
    * An interface for objects that have administrative settings.
    */
public abstract class AdminPropertiesAdminPOA extends org.omg.PortableServer.Servant
 implements CosNotification.AdminPropertiesAdminOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("get_admin", new java.lang.Integer (0));
    _methods.put ("set_admin", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /**
         * Returns the current administrative settings for this object.
         * @returns A sequence of name-value pairs defining the administrative 
         * settings.
         */
       case 0:  // CosNotification/AdminPropertiesAdmin/get_admin
       {
         CosNotification.Property $result[] = null;
         $result = this.get_admin ();
         out = $rh.createReply();
         CosNotification.PropertySeqHelper.write (out, $result);
         break;
       }


  /**
         * Sets the administrative settings for this object.
         * @parm <code>admin</code> - A sequence of desired name-value pairs
         * defining the administrative settings.
         * @raises UnsupportedAdmin If any of the desired setting are not
         * available.
         */
       case 1:  // CosNotification/AdminPropertiesAdmin/set_admin
       {
         try {
           CosNotification.Property admin[] = CosNotification.AdminPropertiesHelper.read (in);
           this.set_admin (admin);
           out = $rh.createReply();
         } catch (CosNotification.UnsupportedAdmin $ex) {
           out = $rh.createExceptionReply ();
           CosNotification.UnsupportedAdminHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:omg.org/CosNotification/AdminPropertiesAdmin:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AdminPropertiesAdmin _this() 
  {
    return AdminPropertiesAdminHelper.narrow(
    super._this_object());
  }

  public AdminPropertiesAdmin _this(org.omg.CORBA.ORB orb) 
  {
    return AdminPropertiesAdminHelper.narrow(
    super._this_object(orb));
  }


} // class AdminPropertiesAdminPOA
