package CosNotification;


/**
* CosNotification/AdminPropertiesAdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/


/**
    * An interface for objects that have administrative settings.
    */
public interface AdminPropertiesAdminOperations 
{

  /**
         * Returns the current administrative settings for this object.
         * @returns A sequence of name-value pairs defining the administrative 
         * settings.
         */
  CosNotification.Property[] get_admin ();

  /**
         * Sets the administrative settings for this object.
         * @parm <code>admin</code> - A sequence of desired name-value pairs
         * defining the administrative settings.
         * @raises UnsupportedAdmin If any of the desired setting are not
         * available.
         */
  void set_admin (CosNotification.Property[] admin) throws CosNotification.UnsupportedAdmin;
} // interface AdminPropertiesAdminOperations
