package CosNotification;


/**
* CosNotification/AnyOrder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/

public interface AnyOrder
{
  public static final short value = (short)(0);
}
