package CosNotification;

/**
* CosNotification/EventHeaderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/

public final class EventHeaderHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotification.EventHeader value = null;

  public EventHeaderHolder ()
  {
  }

  public EventHeaderHolder (CosNotification.EventHeader initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotification.EventHeaderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotification.EventHeaderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotification.EventHeaderHelper.type ();
  }

}
