package CosNotification;


/**
* CosNotification/LifoOrder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/

public interface LifoOrder
{

  // DiscardPolicy takes on the same values as OrderPolicy, plus
  public static final short value = (short)(4);
}
