package CosNotification;


/**
* CosNotification/MaxConsumers.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/

public interface MaxConsumers
{

  // MaxQueueLength takes on a value of type long
  public static final String value = "MaxConsumers";
}
