package CosNotification;


/**
* CosNotification/Priority.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/

public interface Priority
{

  // Can take on the same values as EventReliability
  public static final String value = "Priority";
}
