package CosNotification;

/**
* CosNotification/QoSAdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/


/**
    * An interface for objects that have quality of service settings.
    */
public final class QoSAdminHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotification.QoSAdmin value = null;

  public QoSAdminHolder ()
  {
  }

  public QoSAdminHolder (CosNotification.QoSAdmin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotification.QoSAdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotification.QoSAdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotification.QoSAdminHelper.type ();
  }

}
