package CosNotification;


/**
* CosNotification/Timeout.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/

public interface Timeout
{

  // StopTime takes a value of type TimeBase::UtcT.
  public static final String value = "Timeout";
}
