package CosNotification;


/**
* CosNotification/UnsupportedAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, June 15, 2016 7:24:32 PM COT
*/

public final class UnsupportedAdmin extends org.omg.CORBA.UserException
{
  public CosNotification.PropertyError admin_err[] = null;

  public UnsupportedAdmin ()
  {
    super(UnsupportedAdminHelper.id());
  } // ctor

  public UnsupportedAdmin (CosNotification.PropertyError[] _admin_err)
  {
    super(UnsupportedAdminHelper.id());
    admin_err = _admin_err;
  } // ctor


  public UnsupportedAdmin (String $reason, CosNotification.PropertyError[] _admin_err)
  {
    super(UnsupportedAdminHelper.id() + "  " + $reason);
    admin_err = _admin_err;
  } // ctor

} // class UnsupportedAdmin
