package CosTrading;


/**
* CosTrading/Admin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosTrading.idl
* Wednesday, June 15, 2016 7:24:33 PM COT
*/


/** This interface is used to manage the various policies
 * and constraints applied by the trader.
 */
public interface Admin extends AdminOperations, CosTrading.TraderComponents, CosTrading.SupportAttributes, CosTrading.ImportAttributes, CosTrading.LinkAttributes
{
} // interface Admin
