package CosTrading;


/**
* CosTrading/LookupHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosTrading.idl
* Wednesday, June 15, 2016 7:24:33 PM COT
*/


/** This interface is used to query the trader and retrieve
 * offers which match specified conditions and constraints.
 */
abstract public class LookupHelper
{
  private static String  _id = "IDL:omg.org/CosTrading/Lookup:1.0";

  public static void insert (org.omg.CORBA.Any a, CosTrading.Lookup that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CosTrading.Lookup extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CosTrading.LookupHelper.id (), "Lookup");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CosTrading.Lookup read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LookupStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CosTrading.Lookup value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CosTrading.Lookup narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CosTrading.Lookup)
      return (CosTrading.Lookup)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CosTrading._LookupStub stub = new CosTrading._LookupStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CosTrading.Lookup unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CosTrading.Lookup)
      return (CosTrading.Lookup)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CosTrading._LookupStub stub = new CosTrading._LookupStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
