package CosTrading;


/**
* CosTrading/NotImplemented.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosTrading.idl
* Wednesday, June 15, 2016 7:24:33 PM COT
*/

public final class NotImplemented extends org.omg.CORBA.UserException
{

  public NotImplemented ()
  {
    super(NotImplementedHelper.id());
  } // ctor


  public NotImplemented (String $reason)
  {
    super(NotImplementedHelper.id() + "  " + $reason);
  } // ctor

} // class NotImplemented
