package CosTrading;


/**
* CosTrading/OfferSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosTrading.idl
* Wednesday, June 15, 2016 7:24:33 PM COT
*/

abstract public class OfferSeqHelper
{
  private static String  _id = "IDL:omg.org/CosTrading/OfferSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, CosTrading.Offer[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CosTrading.Offer[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = CosTrading.OfferHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (CosTrading.OfferSeqHelper.id (), "OfferSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CosTrading.Offer[] read (org.omg.CORBA.portable.InputStream istream)
  {
    CosTrading.Offer value[] = null;
    int _len0 = istream.read_long ();
    value = new CosTrading.Offer[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = CosTrading.OfferHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CosTrading.Offer[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      CosTrading.OfferHelper.write (ostream, value[_i0]);
  }

}
