package CosTrading;


/**
* CosTrading/Proxy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosTrading.idl
* Wednesday, June 15, 2016 7:24:33 PM COT
*/


/** This interface supports proxy offers.
 * It is not yet supported.
 */
public interface Proxy extends ProxyOperations, CosTrading.TraderComponents, CosTrading.SupportAttributes
{
} // interface Proxy
