package aSAP;


/**
* aSAP/ASAP_T.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from aSAP.idl
* Wednesday, June 15, 2016 7:24:30 PM COT
*/

public final class ASAP_T implements org.omg.CORBA.portable.IDLEntity
{
  public globaldefs.NameAndStringValue_T name[] = null;
  public String userLabel = null;
  public String nativeEMSName = null;
  public String owner = null;
  public boolean notModifiable = false;
  public aSAP.AlarmSeverityAssignment_T alarmSeverityAssignmentList[] = null;
  public globaldefs.NameAndStringValue_T additionalInfo[] = null;

  public ASAP_T ()
  {
  } // ctor

  public ASAP_T (globaldefs.NameAndStringValue_T[] _name, String _userLabel, String _nativeEMSName, String _owner, boolean _notModifiable, aSAP.AlarmSeverityAssignment_T[] _alarmSeverityAssignmentList, globaldefs.NameAndStringValue_T[] _additionalInfo)
  {
    name = _name;
    userLabel = _userLabel;
    nativeEMSName = _nativeEMSName;
    owner = _owner;
    notModifiable = _notModifiable;
    alarmSeverityAssignmentList = _alarmSeverityAssignmentList;
    additionalInfo = _additionalInfo;
  } // ctor

} // class ASAP_T
