package performance;


/**
* performance/PerformanceManagementMgr_IOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from performance.idl
* Wednesday, June 15, 2016 7:24:40 PM COT
*/


/**
   * <p>The PerformanceManagementMgr_I is used to gain access to operations
   * which deal with performance Monitoring</p>
   *
   * <p>A handle to an instance of this interface is gained via the
   * emsSession::EmsSession_I::getManager() operation in 
   * managerInterface when the managerName "PerformanceManagement" is used.</p>
   **/
public interface PerformanceManagementMgr_IOperations  extends common.Common_IOperations
{

  /**
     * <p>This operation allows the NMS to request, from the EMS, the set
     * of PM parameters supported by a particular ME at a specific layer.<p>
     *
     * <br>globaldefs::NamingAttributes_T meName: Gives the name of the managed 
     * element
     * <br>transmissionParameters::LayerRate layerRate: Gives the layerRate 
     * considered.
     * <br>PMParameterList pmParameterList This out parameter contains the set 
     * of PM parameters that are supported by the ME referred to.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised if the EMS does not support this service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of a non-specific EMS internal 
     *  failure<br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
     * EXCPT_INVALID_INPUT - Raised when meName does not reference an 
     *  managedElement object or layerRate contains undefined rates<br>
     * EXCPT_ENTITY_NOT_FOUND - Raised when meName references object which does 
     *  not exist<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managedElement is 
     * lost<br>
     * <br>
     **/
  void getMEPMcapabilities (globaldefs.NameAndStringValue_T[] meName, short layerRate, performance.PMParameterList_THolder pmParameterList) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation instructs the EMS to turn off PM data collection for a 
     * list of measurement points. Within the request for each measurement point, 
     * one may specify the granularity (15min, 24h, NA, etc.) and location 
     * (nearEnd and/or farEnd and/or bidirectional) for the PM parameters that are 
     * to be deactivated.<p>
     * <p>Disabling is done on a best-effort basis. If PM could not be disabled
     * for a subset of cases in
     * the PMTPSelectList a  list identifying this subset is returned.</p>
     * <p>PM collection stops immediately, i.e., before the completion of the 
     * current monitoring period. This may lead to incomplete 
     * collection periods. If PM collection was never started for this TP, the 
     * operation is considered successful.</p>
     *
     * <br>PMTPSelectList_T pmTPSelectList: This struct contains the relevant 
     * data for the disablePMData request. It must not be empty.
     * <br>PMTPSelectList_T failedTPSelectList: List of points which were not 
     * completely disabled. An empty list indicates that the total request was 
     * successful.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised if the EMS does not support this service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of a non-specific EMS internal 
     *  failure<br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
     * EXCPT_INVALID_INPUT - Raised if pmTPSelectList is empty or contains invalid 
     *  data<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managedElement is 
     *  lost<br>
     * <br>
     **/
  void disablePMData (performance.PMTPSelect_T[] pmTPSelectList, performance.PMTPSelectList_THolder failedTPSelectList) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation instructs the EMS to enable (turn on) PM data collection
     * for a list of measurement points. Within the request for each measurement 
     * point, one may specify the granularity (15min, 24h, NA, etc.) and location 
     * (nearEnd and/or farEnd and/or bidirectional) for the PM parameters that  
     * are to be activated.</p>
     *
     * <p>Enabling is done on best-effort basis. If PM could not be enabled
     * for a subset of cases in the pmTPSelectList, a list identifying this  
     * subset is returned.</p>
     *
     * <p>PM data collection starts immediately, i.e., before the completion of 
     * the current hour monitoring period. This may lead to  
     * incomplete collection periods. If PM collection was already on for a TP,
     * the operation is considered successful.</p>
     *
     * <br>PMTPSelectList_T pmTPSelectList: This struct contains the relevant 
     * data for the enablePMData request. This must not be empty.
     * <br>PMTPSelectList_T failedTPSelectList: List of points which were not 
     * completely enabled. An empty list indicates that the total request was 
     * successful.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised if the EMS does not support this service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of a non-specific EMS internal 
     *  failure<br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
     * EXCPT_INVALID_INPUT - Raised if pmTPSelectList is empty or contains invalid 
     *  data<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managedElement is 
     *  lost<br>
     * EXCPT_CAPACITY_EXCEEDED - Raised when the maximum number of simultaneously 
     *  enabled monitoring points is exceeded<br>
     * <br>
     **/
  void enablePMData (performance.PMTPSelect_T[] pmTPSelectList, performance.PMTPSelectList_THolder failedTPSelectList) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation instructs the EMS to clear (reset) the PM registers
     * for a list of measurement points. Within the request for each measurement 
     * point, one may specify the granularity (15min, 24h, NA, etc.) and location 
     * (nearEnd and/or farEnd and/or bidirectional) for the PM registers that are 
     * to be reset.</p>
     *
     * <p>Clearing PM gauge minimum, maximum, and average registers means to reset 
     * them to the current measurement; for the actual gauge measurement, it has 
     * no effect. This is not considered a failure case.</p>
     *
     * <p>Clearing PM registers is done on best-effort basis. If registers could 
     * not be completely cleared for a subset of cases in the pmTPSelectList, 
     * a list identifying this subset is returned.</p>
     *
     * <br>PMTPSelectList_T pmTPSelectList: This struct contains the relevant 
     * data for the clearPMData request. It must not be empty.
     * <br>PMTPSelectList_T failedTPSelectList: List of points for which PM 
     * registers were not completely cleared. An empty list indicates that the 
     * total request was successful.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised if EMS is unable to support this service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_INVALID_INPUT - Raised if pmTPSelectList is empty or contains invalid 
     *  data<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managedElement is lost
     * <br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
     **/
  void clearPMData (performance.PMTPSelect_T[] pmTPSelectList, performance.PMTPSelectList_THolder failedTPSelectList) throws globaldefs.ProcessingFailureException;

  /**
     * <p>The EMS is requested to inform the NMS about how many hours PM data 
     * records (24h/15min) are held in the EMS. This is the minimum time. If EMS 
     * does not store PM data it is the time supported in the NE (minimum time of 
     * all managed NEs).</p>
     *
     * <br>HoldingTime holdingTime: This out parameter contains the time period 
     * in hours within which 24h PM data records and 15min PM data records may be 
     * retrieved.
     *
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised if EMS is unable to support this service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_NE_COMM_LOSS - Raised if communication is down to an NE and holding 
     *  time cannot be retrieved
     * <br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
     **/
  void getHoldingTime (performance.HoldingTime_THolder holdingTime) throws globaldefs.ProcessingFailureException;

  /** 
     * <p>The purpose of this operation is to retrieve the values of PM thresholds 
     * on a TP/layerRate measurement point. The operation is best-effort. Results 
     * are returned in the out parameter of this operation. The operation can be 
     * applied to a PTP, an FTP or CTP. The NMS requests the TCA parameters for 
     * the particular TP and granularity specified.</p>
     *
     * <br>globaldefs::NamingAttributes_T tpName: Identification of the TP for 
     * which the values of the TCA parameters are to be retrieved. The termination 
     * point name must be explicit (a generic endpoint specification may not be 
     * used in this case).See <a href=../../../supportingDocumentation/SD1-25_objectNaming.pdf >SD1-25 
     * Object Naming</a> for further details on TP naming.
     * <br>transmissionParameters::LayerRate_T layerRate: LayerRate for which 
     * the values of the TCA parameters are to be retrieved.
     * <br><b>in</b>  Granularity_T granularity: Granularity for which the TCA 
     * parameters are to be retrieved
     * <br><b>out</b> TCAParameters_T tcaParameter: Result of the operation
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised if the EMS does not support this service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of a non-specific EMS internal 
     *  failure<br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
     * EXCPT_INVALID_INPUT - Raised when tpName does not reference a 
     *  terminationPoint object or layerRate contains an undefined rate or 
     *  Granularity contains an undefined value<br>
     * EXCPT_ENTITY_NOT_FOUND - Raised when tpName references an object which 
     *  does not exist<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managedElement is 
     *  lost<br>
     * <br>
     **/
  void getTCATPParameter (globaldefs.NameAndStringValue_T[] tpName, short layerRate, String granularity, performance.TCAParameters_THolder tcaParameter) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation instructs the EMS to store history PM data into a file,
     * and to send that file by FTP (File Transfer Protocol)
     * to the destination as specified in the request. Within the 
     * request a list of TP/layerRate measurement points and a time frame are 
     * specified. For each measurement point, the granularity (15min, 24h, NA, 
     * etc) and location (nearEnd and/or farEnd and/or bidirectional) may be 
     * specified. A filtered set (scoped by the input parameter pmParameters) of 
     * PM parameters collected for a particular TP/layerRate measurement point for 
     * the granularity, location and time window specified is made available.</p>
     *
     * <p>Measurement intervals and the given time frame are considered as half 
     * open intervals to the right, i.e. startTime <= t < endTime.</p>
     *
     * <p>A particular historic measurement interval (of duration
     * 15 min resp. 24 h) is defined to be covered by the specified time
     * frame if there is a non empty intersection between the measurement
     * interval and the given time frame, i.e.
     * <br>endTime[PM record] > startTime[request parameter] AND<br>
     * <br>startTime[PM record] &lt; endTime[request parameter]<br>
     * PM data are returned for all covered measurement intervals.</p>
     *
     * <p>For records partly included in the time frame specified, PM data will be 
     * returned. In case a history bin has incomplete PM measurement data (for 
     * instance because PM data collection was disabled for some time period(s) 
     * within the bin's time span), the particular measurement period will be 
     * marked as incomplete.</p>
     *
     * <p>If the forceUpload parameter is true,
     * the EMS is to upload the data for all the specified collection periods 
     * (provided they do exist in the MEs) and provide the entire PM data 
     * requested. If the forceUpload parameter is false,
     * measurement intervals within the specified time frame for which
     * PM data has been collected in the ME but not yet uploaded to the
     * EMS will be included in the PM file with status "Unavailable",
     * however without valid PM data.  </p>
     *
     * <p>Performance Monitoring Data transfer normally involves huge amounts of 
     * data. The capability to send PM data to a controlled destination other than 
     * the NMS allows for flexibility 
     * in the choice of the PM data file format, the particular file transfer 
     * protocol (including the possibility to apply data compression techniques) 
     * and the destination machine so as to make optimal use of the available data 
     * network capacity. The file transfer protocol to transfer PM data is the FTP 
     * protocol.</p>
     *
     * <p>This operation is asynchrounous and is not required to wait until the PM 
     * data is extracted or until the FTP transfer is over before it returns.
     * Notifications can be generated to inform the NMS of the progress of the 
     * transfer.  See
     * <a href=../../../supportingDocumentation/SD1-26_OMGServicesUsage.pdf >SD1-26 Notification 
     * Service and Telecoms Log Service Usage</a> for details.</p>
     *
     * <p>Performance monitoring data on multiple TPs of multiple MEs is 
     * transferred in one data file. This PM data file has the following format:
     * <a href=../../../supportingDocumentation/SD1-30_PMFileFormat.pdf > SD1-30 PM File Format 
     * Definition</a>.</p>
     *
     * <br>Destination_T destination: The destination to which the
     * Performance Monitoring Data file is to be send.
     * <br>String userName: necessary for file transfer with FTP
     * <br>String password: necessary for file transfer with FTP
     * <br>PMTPSelectList_T pmTPSelectList. This parameter specifies which 
     * history PM data to return. If pmTPSelectList is empty, PM data for all 
     * monitored TPs of all MEs managed by the EMS (all layer rates, all 
     * granularities) are stored in the file.
     * <br>PMParameterNameList_T pmParameters. This parameter specifies which PM 
     * parameters within the scope of the pmTPSelectList shall be contained in the 
     * file. An empty list means to store all supported parameters.
     * The returned parameters are best effort, i.e. among the parameters 
     * specified only the subset of supported parameters will be stored.
     * <br>globaldefs::Time_T startTime: Specifies the start of the time window 
     * for collection (included).
     * <br>globaldefs::Time_T endTime: Specifies the end of the time window for 
     * collection (excluded).
     * <br>boolean forceUpload: Specifies if the EMS must upload all available 
     * PM data requested from the MEs.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised if the EMS does not support this service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_INVALID_INPUT - Raised when any input parameter is not well 
     *  formed<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to the NE is down<br>
     * <br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
     **/
  void getHistoryPMData (String destination, String userName, String password, performance.PMTPSelect_T[] pmTPSelectList, String[] pmParameters, String startTime, String endTime, boolean forceUpload) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This allows an NMS to request a filtered set (scoped by the input 
     * parameter pmParameters) of the current PM data
     * for a list of TP measurement points. Within the request for each 
     * measurement point, granularity (15min, 24h, NA, etc.) and location (nearEnd 
     * and/or farEnd and/or bidirectional) may be specified. The operation mode is 
     * best effort.</p>
     *
     * <p>Current data will generally be marked as incomplete, as the 
     * current bin is not completed.
     * If no PM data are available as specified, an empty list is returned.</p>
     * 
     * <p>In order to allow the NMS to deal with a large number of objects
     * this operation uses an iterator. See
     * <a href=../../../supportingDocumentation/SD1-15_iterators.pdf >SD1-15 iterator overview</a>
     * for information on how iterators are used in this interface.</p>
     * 
     * <br>PMTPSelectList_T pmTPSelectList: list of measurement points for which
     * to get the PM data.
     * <br>PMParameterNameList_T pmParameters: specifies which PM parameters 
     * within the scope of the pmTPSelectList shall be returned.
     * An empty list means to return all supported parameters.
     * The returned parameters are best effort, i.e. among the parameters 
     * specified only the subset of supported parameters will be returned.
     * <br>unsigned long how_many: maximum number of PMData to return in the 
     * first batch.
     * <br>PMDataList_T pmDataList: first batch of PMData returned.
     * <br>PMDataIterator_I pmIt: iterator returned to access the remaining 
     * PMData.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised if the EMS does not support this service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_INVALID_INPUT - Raised when pmTPSelectList is empty or contains 
     *  invalid data<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to the Managed Element 
     *  is lost<br>
     * EXCPT_TOO_MANY_OPEN_ITERATORS - Raised when maximum number of iterators 
     *  that the EMS can support has been reached<br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
     * <br>
     **/
  void getAllCurrentPMData (performance.PMTPSelect_T[] pmTPSelectList, String[] pmParameters, int how_many, performance.PMDataList_THolder pmDataList, performance.PMDataIterator_IHolder pmIt) throws globaldefs.ProcessingFailureException;

  /**
     * <p>The purpose of this operation is to modify the values of TCA thresholds 
     * on a TP-layerRate measurement point. It can be applied to a PTP, an FTP or 
     * CTP. For a threshold, a low and high mark may be specified. The NMS 
     * specifies the TP and layerRate, the granularity, and the value(s) of one or 
     * more TCA threshold(s) to be modified.The operation mode is best-effort.
     * If no TCA value is set, a default value will be active.</p>
     * 
     * <br><b>in</b> globaldefs::NamingAttributes_T tpName:
     * Identification of the TP for which the values of one or more TCA parameters 
     * are set. The termination point name must be explicit (a generic endpoint 
     * specification may not be used in this case).
     * See <a href=../../../supportingDocumentation/SD1-25_objectNaming.pdf >SD1-25 
     * Object Naming</a> for further detail on FTP naming.
     * <br><b>inout</b> TCAParameters tcaParameter: The list of TCA
     * ids and corresponding values to be applied to a specific 
     * layer rate are specified by this parameter.
     * The settings that are actually applied are returned in this parameter.<br>
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised if the EMS is unable to support this 
     *  service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_INVALID_INPUT - Raised if tpName does not reference a 
     *  terminationPoint object or at least one field of tcaParameters is not 
     *  valid.<br>
     * EXCPT_ENTITY_NOT_FOUND - Raised when tpName references object which does 
     *  not exist<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managedElement is 
     *  lost<br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
     * <br>
     **/
  void setTCATPParameter (globaldefs.NameAndStringValue_T[] tpName, performance.TCAParameters_THolder tcaParameters) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation will enable TCA generation on a list of TPs and/or MEs
     * at the ME level.</p> 
     *
     * <br>PMTPSelectList_T pmTPSelectList: This struct contains the relevant 
     * data for the enableTCA request. This must not be empty.
     * <br>PMTPSelectList_T failedTPSelectList: List of points which were not 
     * completely enabled.An empty list indicates that the total request was 
     * successful.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised if this operation is not supported<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_INVALID_INPUT - Raised if pmTPSelectList is empty or contains invalid 
     *  data<br>
     * EXCPT_UNABLE_TO_COMPLY - Raised if the EMS is unable to enable TCA for the
     *  specified TPs (pmTPSelectList), i.e. no TPs were enabled.<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managedElement is 
     *  lost<br>
     * <br>
     */
  void enableTCA (performance.PMTPSelect_T[] pmTPSelectList, performance.PMTPSelectList_THolder failedTPSelectList) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation will disable TCA generation on a list of TPs and/or MEs
     * at the ME level.</p>
     *
     * <br>PMTPSelectList_T pmTPSelectList: This struct contains the relevant 
     * data for the enableTCA request. This must not be empty.
     * <br>PMTPSelectList_T failedTPSelectList: List of points which were not 
     * completely disabled. An empty list indicates that the total request was 
     * successful.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised if this operation is not supported<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_INVALID_INPUT - Raised if pmTPSelectList is empty or contains invalid 
     *  data<br>
     * EXCPT_UNABLE_TO_COMPLY - Raised if the EMS is unable to disable TCA for the
     *  specified TPs (pmTPSelectList), i.e. no TPs were disabled<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managedElement is 
     *  lost<br>
     * <br>
     */
  void disableTCA (performance.PMTPSelect_T[] pmTPSelectList, performance.PMTPSelectList_THolder failedTPSelectList) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation gets the set of TPs that are associated with a TCA
     * Parameter Profile.<p>
     *
     * <br><b>in</b> globaldefs::NamingAttributes_T profileName: gives the name 
     * of the profile.
     * <br><b>in</b> unsigned long how_many: maximum number of tpNames to return 
     * in the first batch.
     * <br><b>out</b> globaldefs::NamingAttributesList_T tpNames: provides set 
     * of TPs associated with the profile provided.
     * <br><b>out</b> globaldefs::NamingAttributesIterator_I nameIt: Iterator to
     * retrieve the remaining TP names.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised when EMS does not support this service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_INVALID_INPUT - Raised when input parameter are syntactical 
     *  incorrect<br>
     * EXCPT_ENTITY_NOT_FOUND - Raised when profileName references an object which
     *  does not exist<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managed element is 
     *  lost<br>
     * EXCPT_TOO_MANY_OPEN_ITERATORS - Raised when maximum number of iterators 
     *  that the EMS can support has been reached<br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
     * <br>
     **/
  void getProfileAssociatedTPs (globaldefs.NameAndStringValue_T[] profileName, int how_many, globaldefs.NamingAttributesList_THolder tpNames, globaldefs.NamingAttributesIterator_IHolder nameIt) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation creates a new TCA Parameter Profile.<p>
     *
     * <br><b>in</b> globaldefs::NamingAttributes_T managedElementName: ME under
     *  which the profile is to be created.
     * <br><b>in</b> transmissionParameters::LayerRate_T layerRate: defines the
     * <a href=../../../supportingDocumentation/SD1-17_LayerRates.pdf >SD1-17 layer rate</a> of the 
     * profile to be created.
     * <br><b>in</b> string userLabel: contains the NMS defined name of the 
     * profile to be created.
     * <br><b>in</b> boolean forceUniqueness: if set to TRUE the EMS has to 
     * check if the provided user label is unique in the network element domain.
     * <br><b>in</b> string owner: A label of the owner of the Profile. This is 
     * an optional parameter.
     * <br><b>in</b> globaldefs::NVSList_T additionalInfo: Some additional
     * information may be specified by the NMS.
     * <br><b>in</b> TCAParameterList_T listOfTCAParameter: contains sets of
     * threshold values.
     * <br><b>out</b> TCAParameterProfile_T tcaParameterProfile: EMS returns the
     * new profile to the NMS.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised when EMS does not support this service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_INVALID_INPUT - Raised when input parameter are syntactical 
     *  incorrect<br>
     * EXCPT_ENTITY_NOT_FOUND - Raised when specified managedElement does not 
     *  exist<br>
     * EXCPT_USERLABEL_IN_USE - Raised when the userLabel uniqueness constraint is
     *  not met<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managed element is 
     *  lost<br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
     * <br>
     **/
  void createTCAParameterProfile (globaldefs.NameAndStringValue_T[] managedElementName, short layerRate, String userLabel, boolean forceUniqueness, String owner, globaldefs.NameAndStringValue_T[] additionalInfo, performance.TCAParameter_T[] listOfTCAParameter, performance.TCAParameterProfile_THolder tcaParameterProfile) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation deletes a TCA Parameter Profile.<p>
     *
     * <br><b>in</b> globaldefs::NamingAttributes_T tcaParameterProfileName: 
     * name of the profile to be deleted.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised when EMS does not support this service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_INVALID_INPUT - Raised when input parameter are syntactical 
     *  incorrect<br>
     * EXCPT_ENTITY_NOT_FOUND - Raised when specified Profile does not exist<br>
     * EXCPT_OBJECT_IN_USE - Raised when Profile is still assigned to at least
     *  one TP<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managed element is 
     *  lost<br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
     * <br>
     **/
  void deleteTCAParameterProfile (globaldefs.NameAndStringValue_T[] tcaParameterProfileName) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation gets all threshold values of a TCA Parameter Profile.<p>
     *
     * <br><b>in</b> globaldefs::NamingAttributes_T tcaParameterProfileName: 
     * name of the profile to be retrieved.
     * <br><b>out</b> TCAParameterProfile_T tcaParameterProfile: contains the 
     * sets of threshold values.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised when EMS does not support this service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_INVALID_INPUT - Raised when input parameter are syntactical #
     *  incorrect<br>
     * EXCPT_ENTITY_NOT_FOUND - Raised when specified Profile does not exist<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managed element is 
     *  lost<br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
     * <br>
     **/
  void getTCAParameterProfile (globaldefs.NameAndStringValue_T[] tcaParameterProfileName, performance.TCAParameterProfile_THolder tcaParameterProfile) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation configures all threshold values of a TCA Parameter 
     * Profile and overwrites all the existing threshold values of the profile 
     * with the new provided threshold values.
     * All threshold values of all TPs associated to this Profile will be changed
     * according to the new values.
     * Note: This includes also deletion of thresholds if the threshold is no 
     * longer contained in the provided list of TCA Parameters.
     * The EMS has to return all TPs that could not be changed to the new 
     * threshold values due to some error reasons.<p>
     *
     * <br><b>in</b> globaldefs::NamingAttributes_T tcaParameterProfileName: 
     * name of the profile to be configured.
     * <br><b>in</b> TCAParameterList_T listOfTCAParameter: contains sets of
     * threshold values to change the Profile completely.
     * <br><b>in</b> unsigned long how_many: maximum number of failedTPs to 
     * return in the first batch.
     * <br><b>out</b> TCAParameterProfile_T tcaParameterProfile: returns the
     * changed TCA Parameter Profile.
     * <br><b>out</b> globaldefs::NamingAttributesList_T failedTPList: set of
     * TPs that could not be changed to the new threshold values.
     * <br><b>out</b> globaldefs::NamingAttributesIterator_I nameIt: Iterator to
     * retrieve the remaining failedTP names.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised when EMS does not support this service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_INVALID_INPUT - Raised when input parameter are syntactical 
     *  incorrect<br>
     * EXCPT_ENTITY_NOT_FOUND - Raised when TCA Parameter Profile to be changed 
     *  does not exist<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managed element is 
     *  lost<br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
     * <br>
     **/
  void setTCAParameterProfile (globaldefs.NameAndStringValue_T[] tcaParameterProfileName, performance.TCAParameter_T[] listOfTCAParameter, int how_many, performance.TCAParameterProfile_THolder tcaParameterProfile, globaldefs.NamingAttributesList_THolder failedTPList, globaldefs.NamingAttributesIterator_IHolder nameIt) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation gets all TCA Parameter Profile names regardless of 
     * whether the profile is assigned to a TP or not.<p>
     *
     * <br><b>in</b> globaldefs::NamingAttributes_T meName: name of the Network
     * Element containing the Profiles.
     * <br><b>in</b> unsigned long how_many: maximum number of 
     * tcaParameterProfile names to return in the first batch.
     * <br><b>out</b> globaldefs::NamingAttributesList_T 
     * tcaParameterProfileNames: contains the names of the existing TCA Parameter 
     * Profiles.
     * <br><b>out</b> globaldefs::NamingAttributesIterator_I nameIt: Iterator to
     * retrieve the remaining tcaParameterProfile names.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised when EMS does not support this service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_INVALID_INPUT - Raised when input parameter are syntactical 
     *  incorrect<br>
     * EXCPT_ENTITY_NOT_FOUND - Raised when specified managed element does not 
     *  exist<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managed element is 
     *  lost<br>
     * EXCPT_TOO_MANY_OPEN_ITERATORS - Raised when maximum number of iterators 
     *  that the EMS can support has been reached<br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
     * <br>
     **/
  void getAllTCAParameterProfileNames (globaldefs.NameAndStringValue_T[] meName, int how_many, globaldefs.NamingAttributesList_THolder tcaParameterProfileNames, globaldefs.NamingAttributesIterator_IHolder nameIt) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation returns the PM history data on a specified list of 
     * TPs.<p>
     *
     * <br>PMTPSelectList_T pmTPSelectList: This struct contains the relevant 
     * data to identify the TPs from which to collect. This must not be empty.
     * <br>PMParameterNameList_T pmParameters. This parameter specifies which PM 
     * parameters within the scope of the pmTPSelectList shall be contained in the 
     * returned data. An empty list means all supported parameters should be 
     * returned. The returned parameters are best effort, i.e. among the 
     * parameters specified only the subset of supported parameters will be 
     * returned.
     * <br>globaldefs::Time_T startTime: Specifies the start of the time window 
     * for collection (included).
     * <br>globaldefs::Time_T endTime: Specifies the end of the time window for 
     * collection (excluded).
     * <br>unsigned long how_many: maximum number of PMData to return in the 
     * first batch.
     * <br>PMDataList_T pmDataList: first batch of PMData returned.
     * <br>PMDataIterator_I pmIt: iterator returned to access the remaining 
     * PMData.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised if the EMS does not support this service<br>
     * EXCPT_UNABLE_TO_COMPLY - Raised when EMS does not support history PM for 
     *  the time specified by NMS<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_INVALID_INPUT - Raised when any input parameter is not well 
     *  formed<br>
     * EXCPT_ENTITY_NOT_FOUND - Raised when one of the TP does not exist<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to the NE is down<br>
     * EXCPT_TOO_MANY_OPEN_ITERATORS - Raised when maximum number of iterators 
     *  that the EMS can support has been reached<br>
     **/
  void getTPHistoryPMData (performance.PMTPSelect_T[] pmTPSelectList, String[] pmParameters, String startTime, String endTime, int how_many, performance.PMDataList_THolder pmDataList, performance.PMDataIterator_IHolder pmIt) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation allows an NMS to retrieve all PMPs contained in a TP or 
     * ME specified.</p> 
     *
     * <p>In order to allow the NMS to deal with a large number of objects,
     * this operation uses an iterator. See
     * <a href=../../../supportingDocumentation/SD1-15_iterators.pdf >SD1-15 iterator overview</a>
     * for information on how iterators are used in this interface.</p>
     *
     * <br>globaldefs::NamingAttributes_T name: The name of the object to which 
     * this selection applies. This may be: 
     * <ul>
     * <li>ManagedElement: The selection applies to all termination points  
     * contained within the ManagedElement.</li>
     * <li>TerminationPoint: The selection applies only to the named termination 
     * point which will be a PTP, FTP or a CTP. Unlike the case for 
     * managedElement, the operation will not apply to any contained TPs when a 
     * PTP, FTP or CTP is specified.</li>
     * </ul>
     * <br>performance::PMPList_T pmpList nameList: First batch of PMPs. 
     * <br>performance::PMPIterator_I pmpIt: Iterator to retrieve remaining 
     * PMPs.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised if an EMS does not implement this 
     *  operation<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_INVALID_INPUT - Raised when references an object of type 
     *  other than ME or TP<br>
     * EXCPT_ENTITY_NOT_FOUND - Raised when tpOrMeName references an object 
     *  that does not exist<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managedElement is 
     *  lost<br>
     * EXCPT_TOO_MANY_OPEN_ITERATORS - Raised when maximum number of iterators 
     *  that the EMS can support has been reached<br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
     * <br>
     **/
  void getAllPMPs (globaldefs.NameAndStringValue_T[] tpOrMeName, int how_many, performance.PMPList_THolder pmpList, performance.PMPIterator_IHolder pmpIt) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation has exactly the same behaviour as 
     * getAllPMPs(), but instead of returning the 
     * entire object structures, this operation returns their names.</p>
     *
     * <p>In order to allow the NMS to deal with a large number of objects,
     * this operation uses an iterator. See
     * <a href=../../../supportingDocumentation/SD1-15_iterators.pdf >SD1-15 iterator overview</a>
     * for information on how iterators are used in this interface.</p>
     *
     * <br>globaldefs::NamingAttributes_T name: The name of the object to which 
     * this selection applies. This may be: 
     * <ul>
     * <li>ManagedElement: The selection applies to all termination points  
     * contained within the ManagedElement.</li>
     * <li>TerminationPoint: The selection applies only to the named termination 
     * point which will be a PTP, FTP or a CTP. Unlike the case for 
     * managedElement, the operation will not apply to any contained TPs when a 
     * PTP, FTP or CTP is specified.</li>
     * </ul>
     * <br>unsigned long how_many: Maximum number of PMP names to return
     * in the first batch.
     * <br>globaldefs::NamingAttributesList_T nameList: First batch of PMP 
     * names.
     * <br>globaldefs::NamingAttributesIterator_I nameIt: Iterator to retrieve 
     * the remaining PMP names.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException
     * As for getAllPMPs().
     **/
  void getAllPMPNames (globaldefs.NameAndStringValue_T[] tpOrMeName, int how_many, globaldefs.NamingAttributesList_THolder nameList, globaldefs.NamingAttributesIterator_IHolder nameIt) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation adds/removes TCA Parameter Profiles to/from the TP.
     * The new threshold values contained in the added profiles will be copied to 
     * the corresponding PMPs of the TP. The addition of an already associated 
     * profile to a TP overwrites the corresponding thresholds in the PMPs of the 
     * TP. The threshold values that have been configured via a profile to be 
     * removed will be kept in the PMPs.</p>
     * 
     * <p>Notes:<ul>
     * <li>No further automatic updating based on changes in the profile will be 
     * done.</li>
     * <li>This operation can also be used to align the TCA Thresholds of all PMPs 
     * contained in the TP with the threshold values contained in the associated 
     * TCA Parameter Profile and is therefore idempotent.</li></ul><p>
     *
     * <br>globaldefs::NamingAttributes_T tpName: The name of the TP to which to 
     * assign the pointer to the TCA parameter profile.
     * <br><b>in</b> globaldefs::NamingAttributes_T addTCAParameterProfile: the 
     * name of the TCAParameterProfile to be added to this TP.
     * <br><b>in</b> globaldefs::NamingAttributes_T removeTCAParameterProfile: 
     * the name of the TCAParameterProfile to be removed from this TP.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised when EMS does not support this service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_INVALID_INPUT - Raised when input parameter are syntactical 
     *  incorrect<br>
     * EXCPT_ENTITY_NOT_FOUND - - Raised when tpName references an object that 
     *  does not exist or when TCAParameterProfile to be assigned 
     *  does not exist<br>
     * EXCPT_OBJECT_IN_USE - Raised when TCAParameterProfile of same Layer is 
     *  already assigned to the TP<br>
     * EXCPT_UNABLE_TO_COMPLY - Raised when threshold values in the TP could not 
     *  be configured<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managed element is 
     *  lost<br>
     * <br>
     **/
  void setTCAParameterProfilePointer (globaldefs.NameAndStringValue_T[] tpName, globaldefs.NameAndStringValue_T[] addTCAParameterProfile, globaldefs.NameAndStringValue_T[] removeTCAParameterProfile) throws globaldefs.ProcessingFailureException;

  /**
     * <p>This operation allows an NMS to request all the TCA parameter 
     * profiles associated with the specified managed element.</p>
     *
     * <p>In order to allow the NMS to deal with a large number of 
     * objects, this operation uses an iterator. See
     * <a href=../../../supportingDocumentation/SD1-15_iterators.pdf >SD1-15 iterator overview</a>
     * for information on how iterators are used in this interface.</p>
     *
     * <br>globaldefs::NamingAttributes_T metName: Name of the 
     * managed element containing the TCA parameter profiles.
     * <br>unsigned long how_many: Maximum number of TCA parameter 
     * profiles to return in the first batch.
     * <br>TCAParameterProfileList_T tcaParameterProfileList: The first batch of 
     * TCA parameter profiles.
     * <br>managedElement::TCAParameterProfileIterator_I tcaParameterProfileIt: 
     * Iterator to retrieve the remaining TCA parameter profiles.
     * <br><b>Raises</b> globaldefs::ProcessingFailureException <br>
     * EXCPT_NOT_IMPLEMENTED - Raised when the EMS does not support this 
     *  service<br>
     * EXCPT_INTERNAL_ERROR - Raised in case of non-specific EMS internal 
     *  failure<br>
     * EXCPT_INVALID_INPUT - Raised when meName does not reference a 
     *  managed element object<br>
     * EXCPT_ENTITY_NOT_FOUND - Raised when meName references an object 
     * that does not exist<br>
     * EXCPT_NE_COMM_LOSS - Raised when communications to managedElement 
     * is lost<br>
     * EXCPT_TOO_MANY_OPEN_ITERATORS - Raised when maximum number of
     * iterators that the EMS can support has been reached<br>
     * EXCPT_UNABLE_TO_COMPLY - If the EMS cannot comply with the request,
     *  and cannot determine the reason it could not comply,
     *  it may raise this exception. <br>
    * <br>
     **/
  void getAllTCAParameterProfiles (globaldefs.NameAndStringValue_T[] meName, int how_many, performance.TCAParameterProfileList_THolder tcaParameterProfileList, performance.TCAParameterProfileIterator_IHolder tcaParameterProfileIt) throws globaldefs.ProcessingFailureException;
} // interface PerformanceManagementMgr_IOperations
