package performance;

/**
* performance/PMMeasurement_THolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from performance.idl
* Wednesday, June 15, 2016 7:24:40 PM COT
*/

public final class PMMeasurement_THolder implements org.omg.CORBA.portable.Streamable
{
  public performance.PMMeasurement_T value = null;

  public PMMeasurement_THolder ()
  {
  }

  public PMMeasurement_THolder (performance.PMMeasurement_T initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = performance.PMMeasurement_THelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    performance.PMMeasurement_THelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return performance.PMMeasurement_THelper.type ();
  }

}
