package performance;


/**
* performance/PMParameter_T.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from performance.idl
* Wednesday, June 15, 2016 7:24:40 PM COT
*/

public final class PMParameter_T implements org.omg.CORBA.portable.IDLEntity
{
  public String pmParameterName = null;
  public String pmLocation = null;

  public PMParameter_T ()
  {
  } // ctor

  public PMParameter_T (String _pmParameterName, String _pmLocation)
  {
    pmParameterName = _pmParameterName;
    pmLocation = _pmLocation;
  } // ctor

} // class PMParameter_T
