package emsSessionFactory;


/**
* emsSessionFactory/EmsSessionFactory_I.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from emsSessionFactory.idl
* Wednesday, June 15, 2016 7:24:35 PM COT
*/


/**
   * <p>There is a single instance of the EmsSessionFactory_I.  It is the 
   * entry point to the server/EMS.
   * This instance the object reference that the client uses to connect to the 
   * server.</p>
   *
   * <p>This interface implements the version interface and will return 
   * the server IDL version when getVersion is called on it.</p>
   **/
public interface EmsSessionFactory_I extends EmsSessionFactory_IOperations, mtnmVersion.Version_I, org.omg.CORBA.portable.IDLEntity 
{
} // interface EmsSessionFactory_I
